### ISSUE TITLE
Strict RTP learning after remote address set to: 10.11.4.5:7777

### ISSUE THREAD

**Issue by jyoti143sahoo** [nimbleape/asterisk-dialogflow-rtp-audioserver#23]
exten = 100,1,Answer()
same = n,Wait(1)
same = n,Playback(hello-world)
same = n,Hangup() 
          
exten => 6001,1,Answer()
same => 2,Dial(6001)
same => n,Hangup()

exten => 1000,1,Answer()
 same =>      n,Stasis(dialogflow,inbound) 
 same =>      n,Hangup()

while dialing on extension number 100 successfully getting "hello world" response.
But when trying to call on 1000 getting the below issue

-- Executing [1000@from-internal:1] Answer("PJSIP/6001-0000000c", "") in new stack
       > 0x7f59c4016e50 -- Strict RTP learning after remote address set to: 157.41.106.54:36894
    -- Executing [1000@from-internal:2] Stasis("PJSIP/6001-0000000c", "dialogflow,inbound") in new stack
    -- Channel PJSIP/6001-0000000c joined 'simple_bridge' stasis-bridge <88f078e1-6c5e-4005-b8d4-39e2247dd648>
       > 0x7f59bc001f20 -- Strict RTP learning after remote address set to: 10.11.4.2:7777
    -- Called 10.11.3.5:7777
    -- UnicastRTP/10.11.3.5:7777-0x7f59bc001380 answered
       > Launching Stasis(dialogflow) on UnicastRTP/10.11.4.2:7777-0x7f59bc001380
    -- Channel UnicastRTP/10.11.3.5:7777-0x7f59bc001380 joined 'simple_bridge' stasis-bridge <88f078e1-6c5e-4005-b8d4-39e2247dd648>
       > 0x7f59c4016e50 -- Strict RTP learning after remote address set to: 127.0.0.1:17084

**Comment by kanishk-mehta** [comment]
Facing the same issue as well. @danjenkins - would be awesome if we could get some help on this. Maybe I'm missing something.

**Comment by vcidst** [comment]
You've posted logs of Asterisk where nothing looks wrong. Maybe you should check out what's happening on the ARI Server or the RTP Audioserver?
